"""empty message

Revision ID: 1d776dd738e
Revises: 76e3484f78
Create Date: 2016-04-27 16:36:09.064838

"""

# revision identifiers, used by Alembic.
revision = '1d776dd738e'
down_revision = '76e3484f78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'tag')
    ### end Alembic commands ###
