"""empty message

Revision ID: 2e8db23de26
Revises: 1d776dd738e
Create Date: 2016-04-27 18:02:51.383860

"""

# revision identifiers, used by Alembic.
revision = '2e8db23de26'
down_revision = '1d776dd738e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
